<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.1.2</Version>
    <Company>Agent Watch</Company>
    <Product>Agent Watch for Windows</Product>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
